const items = [
  { name: "Potion of Healing", power: 10, gold: 3 },
  { name: "Potion of Strength", power: 5, gold: 2 },
  { name: "Potion of Dexterity", power: 5, gold: 2 },
  { name: "Potion of Intelligence", power: 5, gold: 2 },
  { name: "Potion of Wisdom", power: 5, gold: 2 },
  { name: "Potion of Charisma", power: 5, gold: 2 },
  { name: "Scroll of Fireball", power: 15, gold: 5 },
  { name: "Scroll of Lightning Bolt", power: 20, gold: 5 },
  { name: "Scroll of Ice Storm", power: 25, gold: 5 },
  { name: "Amulet of Protection", power: -5, gold: 4 },
  { name: "Amulet of Weakness", power: -10, gold: 4 },
  { name: "Ring of Fire Resistance", power: 5, gold: 4 },
  { name: "Ring of Lightning Resistance", power: 5, gold: 4 },
  { name: "Ring of Cold Resistance", power: 5, gold: 4 },
  { name: "Dagger of Venom", power: 15, gold: 6 },
  { name: "Sword of the Sun", power: 25, gold: 10 },
  { name: "Shield of the Mountain", power: -10, gold: 7 },
  { name: "Boots of Speed", power: 5, gold: 4 },
  { name: "Robe of the Magi", power: 10, gold: 6 },
  { name: "Cloak of Invisibility", power: 15, gold: 10 },
  { name: "Wand of Fear", power: -20, gold: 7 },
  { name: "Wand of Sleep", power: -15, gold: 5 },
  { name: "Staff of Fire", power: 20, gold: 10 },
  { name: "Staff of Lightning", power: 25, gold: 10 },
  { name: "Staff of Ice", power: 30, gold: 10 },
  { name: "Gloves of Strength", power: 5, gold: 4 },
  { name: "Gloves of Dexterity", power: 5, gold: 4 },
  { name: "Gloves of Intelligence", power: 5, gold: 4 },
  { name: "Gloves of Wisdom", power: 5, gold: 4 },
  { name: "Gloves of Charisma", power: 5, gold: 4 },
  { name: "Gloves of Wisdom", power: 5, gold: 3 },
  { name: "Gloves of Charisma", power: 5, gold: 3 },
  { name: "Necklace of Fireballs", power: 25, gold: 10 },
  { name: "Necklace of Lightning Bolts", power: 30, gold: 10 },
  { name: "Necklace of Ice Storms", power: 35, gold: 10 },
  { name: "Necklace of Fireballs", power: 25, gold: 4 },
  { name: "Necklace of Lightning Bolts", power: 30, gold: 7 },
  { name: "Necklace of Ice Storms", power: 35, gold: 7 },
  { name: "Helm of Darkvision", power: 5, gold: 1 },
  { name: "Glasses of True Sight", power: 10, gold: 2 }
];
